apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: rakesh4385/heart-api:latest
          # OR use locally built image:
          # image: heart-api:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
